kube-prometheus-stack:
  ## Create default rules for monitoring the cluster
  ## Disable rules for unreachable components
  ##
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeScheduler: false

  ## Disable component scraping for the kube controller manager, etcd, and kube-scheduler
  ## These components are not reachable on EKS
  ##
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false

  prometheus:
    prometheusSpec:
      ## Prometheus StorageSpec for persistent data on AWS EBS
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      ##
      storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

  prometheusOperator:
    admissionWebhooks:
      failurePolicy: Ignore

grafana:
  sidecar:
    dashboards:
      enabled: true
      defaultFolderName: "General"
      label: grafana_dashboard
      labelValue: "1"
      folderAnnotation: grafana_folder
      searchNamespace: ALL
      provider:
        foldersFromFilesStructure: true

  ## additional configuration options available here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml